"""add email outbox

Revision ID: 0247e807154b
Revises: f1f827619482
Create Date: 2026-08-26 11:03:40.551099

"""
from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision = '0247e807154b'
down_revision = 'f1f827619482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='email_status', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', app.models.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('invite_link_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_link_id'], ['invite_links.id'], name=op.f('fk_email_messages_invite_link_id_invite_links'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages'))
    )
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_messages_invite_link_id'), ['invite_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_messages_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_messages_status'))
        batch_op.drop_index(batch_op.f('ix_email_messages_kind'))
        batch_op.drop_index(batch_op.f('ix_email_messages_invite_link_id'))

    op.drop_table('email_messages')
    # ### end Alembic commands ###
