"""add card theme and layout to events

Revision ID: 88c6b8793704
Revises: f746164f4b37
Create Date: 2026-08-25 07:17:13.537144

"""
from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision = '88c6b8793704'
down_revision = 'f746164f4b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_theme', sa.String(length=32), server_default='classic', nullable=False))
        batch_op.add_column(sa.Column('card_layout', sa.String(length=32), server_default='classic', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('card_layout')
        batch_op.drop_column('card_theme')

    # ### end Alembic commands ###
