"""add restricted invitations and head counts

Revision ID: f746164f4b37
Revises: fc0cd8254d33
Create Date: 2026-08-24 22:21:36.881269

"""
from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision = 'f746164f4b37'
down_revision = 'fc0cd8254d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        # server_default backfills existing rows; without it SQLite refuses to
        # add a NOT NULL column. Existing invitations stay restricted.
        batch_op.add_column(
            sa.Column('restricted', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column('adults_attending', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('children_attending', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.drop_column('children_attending')
        batch_op.drop_column('adults_attending')
        batch_op.drop_column('restricted')

    # ### end Alembic commands ###
