"""add shareable invite links

Revision ID: fc0cd8254d33
Revises: 878c43e40187
Create Date: 2026-08-24 22:08:50.783547

"""
from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision = 'fc0cd8254d33'
down_revision = '878c43e40187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('responded_by', sa.String(length=120), nullable=True),
    sa.Column('responded_at', app.models.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('opened_at', app.models.types.UtcDateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.types.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_invite_links_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_invite_links_group_id_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_links')),
    sa.UniqueConstraint('event_id', 'group_id', name='uq_invite_link_event_group')
    )
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_links_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_links_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_links_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_links_token'))
        batch_op.drop_index(batch_op.f('ix_invite_links_group_id'))
        batch_op.drop_index(batch_op.f('ix_invite_links_event_id'))

    op.drop_table('invite_links')
    # ### end Alembic commands ###
